language: node_js
node_js:
    - 12.16.0
cache: yarn

install:
    - yarn install
    
script:
    - yarn build 

deploy:
    provider: elasticbeakstalk
    region: eu-west-2
    app: vida-care-bi
    env: VidaCareBi-env
    bucket_name: elasticbeanstalk-eu-west-2-653100821739
    bucket_path: vida-care-bi
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

after_deploy:
    - echo "Application Deployed!"