language: node_js
node_js:
    - 12.16.0
cache: yarn

install:
    - yarn install
    
script:
    - yarn test
    - yarn run build 

deploy:
    provider: pages
    skip-cleanup: true
    local_dir: build
    on: 
        branch: master
